#!/bin/bash

current=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -o '[0-9]\+%' | head -1 | tr -d '%')

if [ "$current" -ge 95 ]; then
    pactl set-sink-volume @DEFAULT_SINK@ 100%
else
    pactl set-sink-volume @DEFAULT_SINK@ "$((current + 5))%"
fi
